
#服务端口
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://121.201.80.40:3306/pe?autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
sms:
  local:
    url: http://smssh1.253.com/msg/send/json
    username: N6374474
    password: 11
    sign: 11
  foreign:
    url: 11
    username: 11
    password: 11
    sign: 11

